name: pay_jiggy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.0
  get_it: ^7.6.4
  floor: ^1.4.2
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  json_serializable: ^6.7.1
  serializable: ^2.0.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.7
  bloc: ^8.1.2
  logger: ^2.0.2+1
  animate_do: ^3.3.3
  data_connection_checker_tv: ^0.3.5-nullsafety
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  lottie: ^2.7.0
  local_auth: ^2.1.8
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  intl: ^0.19.0
  file_picker: ^6.2.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.25
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
